In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression, Lasso

from sklearn.metrics import accuracy_score, classification_report

In [ ]:
df=pd.read_csv('/content/sample_data/Group_7_Data_clean_woscale.csv')
df.drop(['Unnamed: 0'],inplace=True,axis=1)

In [ ]:
df

,age,housing,loan,month,day_of_week,duration,campaign,previous,emp.var.rate,cons.price.idx,...,marital_single,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,poutcome_nonexistent,poutcome_success,y
0,56,0,0,6,1,261,1,0,1.1,93.994000,...,0,0,0,0,0,0,0,1,0,0
1,57,0,0,6,1,149,1,0,1.1,93.994000,...,0,0,0,1,0,0,0,1,0,0
2,37,1,0,6,1,226,1,0,1.1,93.994000,...,0,0,0,1,0,0,0,1,0,0
3,40,0,0,6,1,151,1,0,1.1,93.994000,...,0,1,0,0,0,0,0,1,0,0
4,56,0,1,6,1,307,1,0,1.1,93.994000,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73069,43,1,0,6,0,551,1,0,1.1,93.994000,...,0,0,0,0,0,0,1,1,0,1
73070,34,0,0,8,3,371,1,0,-3.4,92.428382,...,0,0,0,0,0,0,0,0,0,1
73071,35,0,0,3,4,551,1,0,1.4,93.918000,...,0,0,0,0,0,0,0,1,0,1
73072,27,0,0,3,1,551,2,0,1.4,93.918000,...,1,0,0,1,0,0,0,1,0,1
73073,27,1,0,9,2,551,1,0,-1.1,94.199000,...,1,0,0,0,0,0,0,1,0,1

In [38]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.linear_model import LinearRegression
# Sequential Forward Selection(sfs)
sfs = SFS(RandomForestClassifier(),
          k_features=22,
          forward=True,
          floating=False,
          scoring = 'accuracy',
          cv = 0)

In [39]:
sample_size = 2000  # Number of samples to select
dfs = df.sample(n=sample_size)
X_sample = dfs.drop('y', axis=1)
y_sample = dfs['y']

In [40]:
sfs.fit(X_sample, y_sample)
sfs.k_feature_names_

('age',
 'housing',
 'loan',
 'month',
 'day_of_week',
 'duration',
 'campaign',
 'previous',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed',
 'job_blue-collar',
 'job_entrepreneur',
 'job_housemaid',
 'job_management',
 'job_retired',
 'job_self-employed',
 'job_services',
 'job_student',
 'poutcome_success')

In [41]:
sf=sfs.k_feature_names_
sf

('age',
 'housing',
 'loan',
 'month',
 'day_of_week',
 'duration',
 'campaign',
 'previous',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed',
 'job_blue-collar',
 'job_entrepreneur',
 'job_housemaid',
 'job_management',
 'job_retired',
 'job_self-employed',
 'job_services',
 'job_student',
 'poutcome_success')

In [42]:
data=df[list(sfs.k_feature_names_)]
data
data1=df['y']
data_new=pd.concat([data,data1],axis=1)

In [43]:
data_new

,age,housing,loan,month,day_of_week,duration,campaign,previous,emp.var.rate,cons.price.idx,...,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,poutcome_success,y
0,56,0,0,6,1,261,1,0,1.1,93.994000,...,0,0,1,0,0,0,0,0,0,0
1,57,0,0,6,1,149,1,0,1.1,93.994000,...,0,0,0,0,0,0,1,0,0,0
2,37,1,0,6,1,226,1,0,1.1,93.994000,...,0,0,0,0,0,0,1,0,0,0
3,40,0,0,6,1,151,1,0,1.1,93.994000,...,0,0,0,0,0,0,0,0,0,0
4,56,0,1,6,1,307,1,0,1.1,93.994000,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73069,43,1,0,6,0,551,1,0,1.1,93.994000,...,0,0,0,0,0,0,0,0,0,1
73070,34,0,0,8,3,371,1,0,-3.4,92.428382,...,0,0,0,0,0,0,0,0,0,1
73071,35,0,0,3,4,551,1,0,1.4,93.918000,...,0,0,0,0,0,0,0,0,0,1
73072,27,0,0,3,1,551,2,0,1.4,93.918000,...,0,0,0,0,0,0,0,0,0,1
73073,27,1,0,9,2,551,1,0,-1.1,94.199000,...,0,0,0,0,0,0,0,0,0,1

In [44]:
X = data_new.drop('y', axis=1)  # Features
y = data_new['y']

In [45]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'n_estimators': [50, 100, 200], 'max_depth': [None, 5, 10], 'min_samples_split': [2, 5, 10]}

model3 = RandomForestClassifier()

grid_search = GridSearchCV(model3, param_grid, cv=5, verbose=2)

grid_search.fit(X1_train, y1_train)

best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_

accuracy_RF_fs_HT = best_estimator.score(X1_test, y1_test)
print(f"Best Parameters: {best_params}")
print(f"Best Model's Accuracy: {accuracy_RF_fs_HT}")

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END max_depth=None, min_samples_split=2, n_estimators=50; total time=   2.2s
[CV] END max_depth=None, min_samples_split=2, n_estimators=50; total time=   2.1s
[CV] END max_depth=None, min_samples_split=2, n_estimators=50; total time=   2.1s
[CV] END max_depth=None, min_samples_split=2, n_estimators=50; total time=   2.2s
[CV] END max_depth=None, min_samples_split=2, n_estimators=50; total time=   2.3s
[CV] END max_depth=None, min_samples_split=2, n_estimators=100; total time=   4.7s
[CV] END max_depth=None, min_samples_split=2, n_estimators=100; total time=   4.2s
[CV] END max_depth=None, min_samples_split=2, n_estimators=100; total time=   4.6s
[CV] END max_depth=None, min_samples_split=2, n_estimators=100; total time=   4.4s
[CV] END max_depth=None, min_samples_split=2, n_estimators=100; total time=   4.2s
[CV] END max_depth=None, min_samples_split=2, n_estimators=200; total time=   9.1s
[CV] END max_depth=None, min_samples_split=2, n_estimators=200; total time=   9.0s
[CV] END max_depth=None, min_samples_split=2, n_estimators=200; total time=   8.5s
[CV] END max_depth=None, min_samples_split=2, n_estimators=200; total time=   9.0s
[CV] END max_depth=None, min_samples_split=2, n_estimators=200; total time=   9.0s
[CV] END max_depth=None, min_samples_split=5, n_estimators=50; total time=   2.0s
[CV] END max_depth=None, min_samples_split=5, n_estimators=50; total time=   2.1s
[CV] END max_depth=None, min_samples_split=5, n_estimators=50; total time=   2.1s
[CV] END max_depth=None, min_samples_split=5, n_estimators=50; total time=   2.3s
[CV] END max_depth=None, min_samples_split=5, n_estimators=50; total time=   2.4s
[CV] END max_depth=None, min_samples_split=5, n_estimators=100; total time=   4.1s
[CV] END max_depth=None, min_samples_split=5, n_estimators=100; total time=   4.2s
[CV] END max_depth=None, min_samples_split=5, n_estimators=100; total time=   4.7s
[CV] END max_depth=None, min_samples_split=5, n_estimators=100; total time=   4.2s
[CV] END max_depth=None, min_samples_split=5, n_estimators=100; total time=   4.1s
[CV] END max_depth=None, min_samples_split=5, n_estimators=200; total time=   8.8s
[CV] END max_depth=None, min_samples_split=5, n_estimators=200; total time=   8.9s
[CV] END max_depth=None, min_samples_split=5, n_estimators=200; total time=   8.4s
[CV] END max_depth=None, min_samples_split=5, n_estimators=200; total time=   8.8s
[CV] END max_depth=None, min_samples_split=5, n_estimators=200; total time=   8.8s
[CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   2.0s
[CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   2.0s
[CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   2.1s
[CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   2.5s
[CV] END max_depth=None, min_samples_split=10, n_estimators=50; total time=   2.2s
[CV] END max_depth=None, min_samples_split=10, n_estimators=100; total time=   4.1s
[CV] END max_depth=None, min_samples_split=10, n_estimators=100; total time=   4.1s
[CV] END max_depth=None, min_samples_split=10, n_estimators=100; total time=   4.7s
[CV] END max_depth=None, min_samples_split=10, n_estimators=100; total time=   4.1s
[CV] END max_depth=None, min_samples_split=10, n_estimators=100; total time=   4.1s
[CV] END max_depth=None, min_samples_split=10, n_estimators=200; total time=   8.6s
[CV] END max_depth=None, min_samples_split=10, n_estimators=200; total time=   8.7s
[CV] END max_depth=None, min_samples_split=10, n_estimators=200; total time=  10.1s
[CV] END max_depth=None, min_samples_split=10, n_estimators=200; total time=   9.5s
[CV] END max_depth=None, min_samples_split=10, n_estimators=200; total time=   8.8s
[CV] END ..max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=2, n_estimators=50; total time=   0.9s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=100; total time=   2.2s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=100; total time=   1.9s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=100; total time=   1.8s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=100; total time=   1.8s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=100; total time=   1.8s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=200; total time=   4.0s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=200; total time=   3.5s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=200; total time=   3.7s
[CV] END .max_depth=5, min_samples_split=2, n_estimators=200; total time=   4.1s
[CV] END ..max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.9s
[CV] END ..max_depth=5, min_samples_split=5, n_estimators=50; total time=   0.9s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=100; total time=   1.7s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=100; total time=   1.8s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=100; total time=   1.8s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=100; total time=   2.3s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=100; total time=   1.8s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=200; total time=   3.5s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=200; total time=   3.5s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=200; total time=   4.2s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=200; total time=   3.5s
[CV] END .max_depth=5, min_samples_split=5, n_estimators=200; total time=   3.5s
[CV] END .max_depth=5, min_samples_split=10, n_estimators=50; total time=   0.9s
[CV] END .max_depth=5, min_samples_split=10, n_estimators=50; total time=   0.9s
[CV] END .max_depth=5, min_samples_split=10, n_estimators=50; total time=   0.9s
[CV] END .max_depth=5, min_samples_split=10, n_estimators=50; total time=   1.1s
[CV] END .max_depth=5, min_samples_split=10, n_estimators=50; total time=   1.2s
[CV] END max_depth=5, min_samples_split=10, n_estimators=100; total time=   1.9s
[CV] END max_depth=5, min_samples_split=10, n_estimators=100; total time=   1.8s
[CV] END max_depth=5, min_samples_split=10, n_estimators=100; total time=   1.8s
[CV] END max_depth=5, min_samples_split=10, n_estimators=100; total time=   1.8s
[CV] END max_depth=5, min_samples_split=10, n_estimators=100; total time=   1.8s
[CV] END max_depth=5, min_samples_split=10, n_estimators=200; total time=   4.0s
[CV] END max_depth=5, min_samples_split=10, n_estimators=200; total time=   3.4s
[CV] END max_depth=5, min_samples_split=10, n_estimators=200; total time=   3.5s
[CV] END max_depth=5, min_samples_split=10, n_estimators=200; total time=   3.7s
[CV] END max_depth=5, min_samples_split=10, n_estimators=200; total time=   4.0s
[CV] END .max_depth=10, min_samples_split=2, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=2, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=2, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=2, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=2, n_estimators=50; total time=   1.4s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   3.4s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   2.9s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, min_samples_split=2, n_estimators=100; total time=   3.1s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   5.9s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   5.7s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   6.9s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   5.9s
[CV] END max_depth=10, min_samples_split=2, n_estimators=200; total time=   6.1s
[CV] END .max_depth=10, min_samples_split=5, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=5, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=5, n_estimators=50; total time=   1.4s
[CV] END .max_depth=10, min_samples_split=5, n_estimators=50; total time=   1.5s
[CV] END .max_depth=10, min_samples_split=5, n_estimators=50; total time=   1.8s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   2.9s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   2.9s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   3.1s
[CV] END max_depth=10, min_samples_split=5, n_estimators=100; total time=   3.1s
[CV] END max_depth=10, min_samples_split=5, n_estimators=200; total time=   5.7s
[CV] END max_depth=10, min_samples_split=5, n_estimators=200; total time=   6.3s
[CV] END max_depth=10, min_samples_split=5, n_estimators=200; total time=   6.0s
[CV] END max_depth=10, min_samples_split=5, n_estimators=200; total time=   6.2s
[CV] END max_depth=10, min_samples_split=5, n_estimators=200; total time=   5.6s
[CV] END max_depth=10, min_samples_split=10, n_estimators=50; total time=   1.4s
[CV] END max_depth=10, min_samples_split=10, n_estimators=50; total time=   1.4s
[CV] END max_depth=10, min_samples_split=10, n_estimators=50; total time=   1.6s
[CV] END max_depth=10, min_samples_split=10, n_estimators=50; total time=   1.7s
[CV] END max_depth=10, min_samples_split=10, n_estimators=50; total time=   1.4s
[CV] END max_depth=10, min_samples_split=10, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, min_samples_split=10, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, min_samples_split=10, n_estimators=100; total time=   2.9s
[CV] END max_depth=10, min_samples_split=10, n_estimators=100; total time=   3.3s
[CV] END max_depth=10, min_samples_split=10, n_estimators=100; total time=   2.8s
[CV] END max_depth=10, min_samples_split=10, n_estimators=200; total time=   5.7s
[CV] END max_depth=10, min_samples_split=10, n_estimators=200; total time=   6.3s
[CV] END max_depth=10, min_samples_split=10, n_estimators=200; total time=   5.7s
[CV] END max_depth=10, min_samples_split=10, n_estimators=200; total time=   6.3s
[CV] END max_depth=10, min_samples_split=10, n_estimators=200; total time=   5.6s
Best Parameters: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
Best Model's Accuracy: 0.9463564830653438